import type { Metadata } from "next";import "./globals.css";



export const metadata: Metadata = {
  title: "Ai Chat Bot",
  description: "Generated by Safiyrahman Jami",
  icons : {
    icon: "logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl"
      lang="en" >
      <body className='bg-[#0a0a0a] text-[#e5e5e5] antialiased'>{children}</body>
    </html>
  );
}
